# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: EzeraTech
email: hello@ezeratech.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.ezeatech.com" # the base hostname & protocol for your site
twitter_username: ezeratech
github_username:  ezeratech
linkedin_username: ezeratech
exclude: ["Rakefile", "Gemfile*"]
gems: [jekyll-paginate, jekyll-paginate-category]
encoding: UTF-8

paginate: 2
paginate_path: "page:num"

category_dir: "_posts"
category_layout: "index.html"

links:
  - title: work
    url: /work/
  - title: blog
    url: /blog/
  - title: contact
    url: /contact.html

# Build settings
markdown: kramdown

# defaults:
#   -
#     scope:
#       path: ""
#       type: "pages"
#     values:
#       layout: "inner-page"
#   -
#     scope:
#       path: "blog"
#       type: "posts"
#     values:
#       layout: "inner-page"
#   -
#     scope:
#       categories: "work"
#       type: "posts"
#     values:
#       layout: "work"
#       permalink: /work/:title.html
